name: set env for profile

on:
  workflow_dispatch:

env:
  DBT_PROFILES_DIR: .
  DBT_BIGQUERY_TOKEN: ${{ secrets.DBT_BIGQUERY_TOKEN }}

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dbt-run
        id: dbt-run
        uses: mwhitaker/dbt-action@set-command
        with:
          dbt_command: "dbt run"
          dbt_project_folder: "dbt_project"
          
      - name: Get the result
        run: echo "${{ steps.dbt-run.outputs.result }}"
        shell: bash

      - name: SendGrid
        uses: peter-evans/sendgrid-action@v1
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_FROM: ${{ secrets.SENDGRID_FROM }}
          SENDGRID_TO: ${{ secrets.SENDGRID_TO }}
